name: Build Test 1
on: 
  # push:
  # pull_request:
  workflow_dispatch:
    # inputs:
    #   cmake_build_type:
    #     required: false
    #     default: Release
    #     type: choice
    #     options:
    #       - Debug
    #       - Release

env:
  MODEL_URL: https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.bin
  MODEL_openvino_URL: https://huggingface.co/Intel/whisper.cpp-openvino-models/resolve/main/ggml-large-v3-models.zip
  MODEL_FILENAME: ggml-large-v3.bin
  AUDIO_URL: https://github.com/fcbond/hkcancor/raw/refs/heads/master/sample/m.mp3
  AUDIO_FILENAME: m.wav
  language: yue
  initial_prompt: 繁體
  CMAKE_BUILD_TYPE: Release

jobs:
    test:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
              include:
                # # macOS

                # - platform: "macos-latest"
                #   name: "MacOS (Arm) - aarch64"
                #   cmake-args: "-DGGML_CCACHE=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=${{ inputs.cmake_build_type }} -DGGML_STATIC=ON"
      
                # Linux cmake
                # - platform: "ubuntu-22.04"
                #   name: "ubuntu-2204-x86_64-cpu-cmake"
                #   build-name: "build-ubuntu-2204-x86_64-cpu-cmake"
                #   cmake-args: "-DGGML_CCACHE=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=${{ inputs.cmake_build_type }} -DGGML_STATIC=ON"

                # # Linux cmake SDL2
                # - platform: "ubuntu-22.04"
                #   name: "ubuntu-2204-x86_64-cpu-cmake-sdl2"
                #   build-name: "build-ubuntu-2204-x86_64-cpu-cmake-sdl2"
                #   cmake-args: "-DWHISPER_SDL2=ON -DCMAKE_BUILD_TYPE=Release"

                # # Linux cmake SDL2 Static
                # - platform: "ubuntu-22.04"
                #   name: "ubuntu-2204-x86_64-cpu-cmake-sdl2-static"
                #   build-name: "build-ubuntu-2204-x86_64-cpu-cmake-sdl2-static"
                #   cmake-args: "-DGGML_CCACHE=OFF -DBUILD_SHARED_LIBS=OFF -DWHISPER_SDL2=ON -DCMAKE_BUILD_TYPE=Release -DGGML_STATIC=ON"

                # Linux cmake SDL2 Static + OpenVINO
                - platform: "ubuntu-22.04"
                  name: "ubuntu-2204-x86_64-cpu-cmake-sdl2-openvino-static"
                  build-name: "build-ubuntu-2204-x86_64-cpu-cmake-sdl2-openvino-static"
                  cmake-args: "-DGGML_CCACHE=OFF -DBUILD_SHARED_LIBS=OFF -DWHISPER_SDL2=ON -DCMAKE_BUILD_TYPE=Release -DGGML_STATIC=ON -DWHISPER_OPENVINO=1"
                  openvino_URL: https://storage.openvinotoolkit.org/repositories/openvino/packages/2023.0/linux/l_openvino_toolkit_ubuntu22_2023.0.0.10926.b4452d56304_x86_64.tgz

                #   # Linux make SDL2 + OpenBLAS
                # - platform: "ubuntu-22.04"
                #   name: "ubuntu-2204-x86_64-cpu-make-sdl2-openblas"
                #   build-name: "build-ubuntu-2204-x86_64-cpu-make-sdl2-openblas"
                #   make-args: "GGML_OPENBLAS=1"
                #   # cmake-args: "-DGGML_CCACHE=OFF -DBUILD_SHARED_LIBS=OFF -DWHISPER_SDL2=ON -DCMAKE_BUILD_TYPE=Release -DGGML_STATIC=ON -DGGML_OPENBLAS=ON"

                # # Linux cmake SDL2 Static
                # - platform: "ubuntu-24.04"
                #   name: "ubuntu-2404-x86_64-cpu-cmake-sdl2-static"
                #   build-name: "build-ubuntu-2404-x86_64-cpu-cmake-sdl2-static"
                #   cmake-args: "-DGGML_CCACHE=OFF -DBUILD_SHARED_LIBS=OFF -DWHISPER_SDL2=ON -DCMAKE_BUILD_TYPE=Release -DGGML_STATIC=ON"

                # - platform: "ubuntu-24.04"
                #   name: "Ubuntu 24.04 - x86_64 - Vulkan"
                #   cmake-args: "-DGGML_VULKAN=ON -DGGML_CCACHE=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=${{ inputs.cmake_build_type }} -DGGML_STATIC=ON"
      
                # # Windows msbuild 1
                # - platform: "windows-2022"
                #   name: "windows-x86_64-cpu-msbuild-1"
                #   build-name: "build-windows-x86_64-cpu-msbuild-1"
                #   cmake-args: "-DGGML_CCACHE=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DGGML_STATIC=ON"

                # # Windows msbuild 1 SDL2 Static
                # - platform: "windows-2022"
                #   name: "windows-x86_64-cpu-msbuild-1-sdl2"
                #   build-name: "build-windows-x86_64-cpu-msbuild-1-sdl2"
                #   cmake-args: "-DGGML_CCACHE=OFF -DBUILD_SHARED_LIBS=OFF -DWHISPER_SDL2=ON -DCMAKE_BUILD_TYPE=Release -DGGML_STATIC=ON"
                #   s2ver: 2.30.7                  

                # Windows msbuild 1 SDL2 Static + OpenVINO
                - platform: "windows-2022"
                  name: "windows-x86_64-cpu-msbuild-1-sdl2-openvino"
                  build-name: "build-windows-x86_64-cpu-msbuild-1-sdl2-openvino"
                  cmake-args: "-DGGML_CCACHE=OFF -DBUILD_SHARED_LIBS=OFF -DWHISPER_SDL2=ON -DCMAKE_BUILD_TYPE=Release -DGGML_STATIC=ON -DWHISPER_OPENVINO=1"
                  s2ver: 2.30.7
                  openvino_URL: https://storage.openvinotoolkit.org/repositories/openvino/packages/2024.4/windows/w_openvino_toolkit_windows_2024.4.0.16579.c3152d32c9c_x86_64.zip

                # - platform: "windows-latest"
                #   name: "Windows - x86_64 - Vulkan"
                #   cmake-args: "-DGGML_VULKAN=ON -DGGML_CCACHE=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=${{ inputs.cmake_build_type }} -DGGML_STATIC=ON"

        runs-on: ${{ matrix.platform }}
        name: ${{ matrix.name }}
        steps:
            - uses: actions/checkout@v4

            - name: Set default env variables for Linux
              if: contains(matrix.platform, 'windows') == false
              run: |
                echo "now=$(TZ="Asia/Hong_Kong" date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
              # echo "CMAKE_BUILD_TYPE=${{ inputs.cmake_build_type || 'Release' }}" >> $GITHUB_ENV

            - name: Set default env variables for Windows
              if: contains(matrix.platform, 'windows')
              run: |
                $now =(Get-Date).ToUniversalTime().AddHours(8).ToString("yyyyMMdd-HHmmss")
                echo "now=$now" >> $env:GITHUB_ENV

              # echo "CMAKE_BUILD_TYPE=${{ inputs.cmake_build_type || 'Release' }}" >> $GITHUB_ENV

            # - name: Prepare Vulkan SDK for Windows
            #   run: |
            #     C:\msys64\usr\bin\wget.exe https://sdk.lunarg.com/sdk/download/1.3.290.0/windows/VulkanSDK-1.3.290.0-Installer.exe -O vulkan.exe
            #     .\vulkan.exe --root C:\vulkan --accept-licenses --default-answer --confirm-command install
            #     echo "VULKAN_SDK=C:\vulkan" >> $env:GITHUB_ENV
            #     Copy-Item -Path "C:\vulkan\Bin\*.dll" -Destination "." -Recurse

            #     # Add Vulkan runtime DLL to PATH
            #     C:\msys64\usr\bin\wget https://sdk.lunarg.com/sdk/download/1.3.290.0/windows/VulkanRT-1.3.290.0-Components.zip -O vulkan_components.exe
            #     7z x vulkan_components.exe
            #     echo "$pwd\VulkanRT-1.3.290.0-Components\x64" | Out-File -FilePath $env:GITHUB_PATH -Append

            #   if: ${{ contains(matrix.platform, 'windows') && contains(matrix.cmake-args, 'DGGML_VULKAN=ON') }}

            # - name: Prepare Vulkan SDK for Linux
            #   run: |
            #     wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
            #     sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-noble.list http://packages.lunarg.com/vulkan/lunarg-vulkan-noble.list
            #     sudo apt update
            #     sudo apt install vulkan-sdk -y
            #     sudo apt-get install -y mesa-vulkan-drivers
            #   if: ${{ contains(matrix.platform, 'ubuntu') && contains(matrix.cmake-args, 'DGGML_VULKAN=ON') }}

            - name: Prepare SDL2 for Linux
              if: contains(matrix.platform, 'ubuntu')
              run: |
                sudo apt update
                echo -e "\nThe current version of libsdl2-dev is  : \n"
                apt show libsdl2-dev | grep "Version  : " | cut -d' ' -f2
                echo -e "\nInstalling libsdl2-dev ... \n"
                sudo apt install -y libsdl2-dev
              # if: ${{ contains(matrix.platform, 'ubuntu') && contains(matrix.cmake-args, 'DWHISPER_SDL2=ON') }}

            - name: Prepare SDL2 for Windows
              run: |
                C:\msys64\usr\bin\wget.exe -qO sdl2.zip https://github.com/libsdl-org/SDL/releases/download/release-${{ matrix.s2ver }}/SDL2-devel-${{ matrix.s2ver }}-VC.zip
                7z x sdl2.zip
                echo "SDL2_DIR=$env:GITHUB_WORKSPACE/SDL2-${{ matrix.s2ver }}/cmake" >> $env:GITHUB_ENV
                echo "`nPATH"
                echo $env:PATH
                echo "`nSDL2_DIR"
                echo $env:SDL2_DIR
                echo "`nGITHUB_ENV"
                echo $env:GITHUB_ENV
                ls
              if: ${{ contains(matrix.platform, 'windows') && contains(matrix.cmake-args, '-DWHISPER_SDL2=ON') }}  

            - name: Prepare OpenBLAS for Linux
              run: |
                sudo apt update
                echo -e "\nThe current version of libopenblas-dev is  : \n"
                apt show libopenblas-dev | grep "Version  : " | cut -d' ' -f2
                echo -e "\nInstalling libsdl2-dev ... \n"
                sudo apt install -y libopenblas-dev
              if: ${{ contains(matrix.platform, 'ubuntu') && contains(matrix.make-args, 'GGML_OPENBLAS=1') }}              

            - name: Prepare OpenVINO for Linux
              run: |
                wget -c "${{ matrix.openvino_URL }}"
                ls -al "$(basename "${{ matrix.openvino_URL }}")"
                tar -xvf "$(basename "${{ matrix.openvino_URL }}")"              
                openvino_folder_root="$(echo "$(basename "${{ matrix.openvino_URL }}")" | sed 's/\.tgz$//')"
                echo -e "\nThe current openvino : $openvino_folder_root\n"
                sudo ./$openvino_folder_root/install_dependencies/install_openvino_dependencies.sh
                source $openvino_folder_root/setupvars.sh
                echo "OpenVINO_DIR=$GITHUB_WORKSPACE/$openvino_folder_root/runtime/cmake" >> $GITHUB_ENV
                echo "openvino_folder_root=$openvino_folder_root" >> $GITHUB_ENV
              if: ${{ contains(matrix.platform, 'ubuntu') && contains(matrix.cmake-args, '-DWHISPER_OPENVINO=1') }}  

            - name: Prepare OpenVINO for Windows
              run: |
                C:\msys64\usr\bin\wget.exe -c ${{ matrix.openvino_URL }}
                ls ("${{ matrix.openvino_URL }}" -split "/" | Select-Object -Last 1)
                7z x ("${{ matrix.openvino_URL }}" -split "/" | Select-Object -Last 1)
                $openvino_folder_root =("${{ matrix.openvino_URL }}" -split "/" | Select-Object -Last 1).Replace(".zip", "")
                echo `n"The current openvino : $openvino_folder_root"`n
                & $openvino_folder_root\setupvars.bat
                echo "OpenVINO_DIR=$env:GITHUB_WORKSPACE\$openvino_folder_root\runtime\cmake" >> $env:GITHUB_ENV
                echo "openvino_folder_root=$openvino_folder_root" >> $env:GITHUB_ENV
              if: ${{ contains(matrix.platform, 'windows') && contains(matrix.cmake-args, '-DWHISPER_OPENVINO=1') }}  

            - name: Download assets on Linux
              if: contains(matrix.platform, 'windows') == false
              run: |
                wget -c ${{ env.MODEL_openvino_URL }}
                7z x "$(basename "${{ env.MODEL_openvino_URL }}")"
              # wget ${{ env.AUDIO_URL }}

            - name: Download assets on Windows
              if: contains(matrix.platform, 'windows')
              run: |
                C:\msys64\usr\bin\wget.exe ${{ env.MODEL_openvino_URL }}
                7z x "$("${{ env.MODEL_openvino_URL }}" -split "/" | Select-Object -Last 1)"
              # C:\msys64\usr\bin\wget.exe ${{ env.AUDIO_URL }}
      
            - name: Platform Test 1
              run: |
                echo ${{ matrix.platform }}
                echo ${{ matrix.build-name }}_${{ env.now }}
                echo "Current Folder : "
                ls
                echo "The environment of current runner : "
                env 

            - name: Ununtu Test 1
              if: contains(matrix.platform, 'ubuntu')
              run: |
                echo -e "\nThe current runner of Github action is : ${{ matrix.platform }}"
                echo -e "\nThe current build name is              : ${{ matrix.build-name }}_${{ env.now }}"
                echo -e "\nThe Current Folder                     : $(pwd) \n"
                ls -al
                echo -e "\nThe path of GITHUB_ENV                 : "
                echo $GITHUB_ENV
                echo -e "\nThe variable of GITHUB_ENV : "
                cat $GITHUB_ENV
                echo -e "\nThe variable of PATH : "
                echo $PATH
                echo -e "\nThe variable of cmake-args : "
                echo ${{ matrix.cmake-args }}
                echo -e "\nThe variable of make-args  : "
                echo ${{ matrix.make-args }}

            - name: Windows Test 1
              if: contains(matrix.platform, 'windows')
              run: |
                echo ${{ matrix.platform }}
                echo ${{ matrix.build-name }}_${{ env.now }}
                echo "`nCurrent Folder : $(pwd)`n"
                ls
                echo `n"The path of GITHUB_ENV : "
                echo $env:GITHUB_ENV
                echo `n"The variable of GITHUB_ENV : "
                echo $env:GITHUB_ENV         
                echo `n"The variable of PATH : "
                $env:PATH -split ';'
                echo `n"The variable of cmake-args : "
                echo ${{ matrix.cmake-args }}
                Get-ChildItem env:

            - name: Configure cmake for Ubuntu
              run: |
                echo -e "\nThe cmake args are: ${{ matrix.cmake-args }}\n"
                cmake -B build ${{ matrix.cmake-args }}
                ls build
              if: ${{ contains(matrix.platform, 'ubuntu') && contains(matrix.cmake-args, '-DCMAKE_BUILD_TYPE=Release') }}  

            - name: Configure cmake for Windows
              run: |
                echo "`nThe cmake args are: ${{ matrix.cmake-args }}`n"
                cmake -B build ${{ matrix.cmake-args }}
                ls build
              if: ${{ contains(matrix.platform, 'windows') && contains(matrix.cmake-args, '-DCMAKE_BUILD_TYPE=Release') }} 

            # - name: Configure
            #   run: |
            #     cmake -B build ${{ matrix.cmake-args }}

            # - name: Build
            #   run: |
            #     cmake --build build --target main --config ${{ inputs.cmake_build_type }}

            - name: Build for Ubuntu (cmake)
              run: |
                cmake --build build -j$(nproc) --config Release
                echo -e "\n The compiled files are : \n"
                ls -al build/bin
              if: ${{ contains(matrix.platform, 'ubuntu') && contains(matrix.cmake-args, '-DCMAKE_BUILD_TYPE=Release') }}

            - name: Build for Ubuntu (make)
              run: |
                echo -e "\nThe make args are: ${{ matrix.make-args }}\n"
                ${{ matrix.make-args }} make -j$(nproc)
                echo -e "\n The compiled files are : \n"
                {
                for file in * ; do
                  if [ -f "$file" ]; then
                    if file "$file" | grep -q "ELF"; then
                      ls -al $file
                    fi
                  fi
                done
                }
              if: ${{ contains(matrix.platform, 'ubuntu') && contains(matrix.make-args, 'GGML_OPENBLAS=1') }}

            - name: Build for Windows (msbuild-1)
              run: |
                cmake --build build --config Release
                ls build\bin\Release     
              if: ${{ contains(matrix.platform, 'windows') && contains(matrix.cmake-args, '-DCMAKE_BUILD_TYPE=Release') }}  

            - name: Copy dll file of openvino (Windows)
              run: |
                cp "$("$("${{ matrix.openvino_URL }}" -split "/" | Select-Object -Last 1)".Replace(".zip", ""))"\runtime\bin\intel64\Release\*.dll build\bin\Release
                cp "$("$("${{ matrix.openvino_URL }}" -split "/" | Select-Object -Last 1)".Replace(".zip", ""))"\runtime\3rdparty\tbb\bin\*.dll build\bin\Release
                ls build\bin\Release     
              if: ${{ contains(matrix.platform, 'windows') && contains(matrix.cmake-args, '-DWHISPER_OPENVINO=1') }}  

            # - name: Test Unix
            #   if: ${{ contains(matrix.platform, 'ubuntu') || contains(matrix.platform, 'macos') }}
            #   run: |
            #       ./build/bin/main -m ${{ env.MODEL_FILENAME }} -f ${{ env.AUDIO_FILENAME }}

            # - name: Test compiled file (Ubuntu) 0
            #   if: contains(matrix.platform, 'ubuntu')
            #   run: |
            #       ./build/bin/main -h

            # - name: Test compiled file (Ubuntu) 1
            #   if: contains(matrix.platform, 'ubuntu')
            #   run: |
            #       time ./build/bin/main -m ${{ env.MODEL_FILENAME }} -f ${{ env.AUDIO_FILENAME }}

            # .\build\bin\Release\main -m ${{ env.MODEL_FILENAME }} -f ${{ env.AUDIO_FILENAME }}

            - name: Save the compiled file (Ubuntu cmake)
              run: |
                mkdir archive
                mkdir archive/${{ matrix.build-name }}_${{ env.now }}
                cp -r build archive/${{ matrix.build-name }}_${{ env.now }}
                ls -al archive/${{ matrix.build-name }}_${{ env.now }}/build
                cd archive 
                tar -cvzf ${{ matrix.build-name }}_${{ env.now }}.tar.gz ${{ matrix.build-name }}_${{ env.now }}
                ls -al ${{ matrix.build-name }}_${{ env.now }}.tar.gz
                cd ..
              if: ${{ contains(matrix.platform, 'ubuntu') && contains(matrix.cmake-args, '-DCMAKE_BUILD_TYPE=Release') }}

            - name: Save the compiled file (Ubuntu make)
              run: |
                mkdir archive
                mkdir archive/${{ matrix.build-name }}_${{ env.now }}
                mkdir archive/${{ matrix.build-name }}_${{ env.now }}/build
                {
                for file in *; do
                  if [ -f "$file" ]; then
                    if file "$file" | grep -q "ELF"; then
                      cp $file archive/${{ matrix.build-name }}_${{ env.now }}/build
                      ls -al archive/${{ matrix.build-name }}_${{ env.now }}/build/$file
                    fi
                  fi
                done
                }
                cd archive 
                tar -cvzf ${{ matrix.build-name }}_${{ env.now }}.tar.gz ${{ matrix.build-name }}_${{ env.now }}
                ls -al ${{ matrix.build-name }}_${{ env.now }}.tar.gz
                cd ..
              if: ${{ contains(matrix.platform, 'ubuntu') && contains(matrix.make-args, 'GGML_OPENBLAS=1') }}

            - name: Save the compiled file (Windows Test 1)
              if: contains(matrix.platform, 'windows')
              run: |
                mkdir archive
                mkdir archive\${{ matrix.build-name }}_${{ env.now }}
                copy -r build archive\${{ matrix.build-name }}_${{ env.now }}
                ls archive\${{ matrix.build-name }}_${{ env.now }}\build
                ls archive\${{ matrix.build-name }}_${{ env.now }}\build\bin\Release

            # - name: Archive the compiled file
            #   if: contains(matrix.platform, 'ubuntu')
            #   uses: actions/upload-artifact@v4
            #   with:
            #     name: ${{ matrix.build-name }}_${{ env.now }}
            #     path: |
            #       archive

            - name: Archive the compiled file (Ubuntu Test 1)
              if: contains(matrix.platform, 'ubuntu')
              uses: actions/upload-artifact@v4
              with:
                name: ${{ matrix.build-name }}_${{ env.now }}
                path: |
                  archive/${{ matrix.build-name }}_${{ env.now }}.tar.gz

            - name: Archive the compiled file (Windows Test 1)
              if: contains(matrix.platform, 'windows')
              uses: actions/upload-artifact@v4
              with:
                name: ${{ matrix.build-name }}_${{ env.now }}
                path: |
                  archive

            - name: Test compiled file (Ubuntu cmake) 1
              run: |
                  ./build/bin/main -h
                  time ./build/bin/main -m "$(echo "$(basename "${{ env.MODEL_openvino_URL }}")" | sed 's/\-models.zip$//').bin" -f ${{ env.AUDIO_FILENAME }} -l ${{ env.language }} --prompt ${{ env.initial_prompt }} -fa
              if: ${{ contains(matrix.platform, 'ubuntu') && contains(matrix.cmake-args, '-DCMAKE_BUILD_TYPE=Release') }}

            - name: Test compiled file (Ubuntu make) 1
              run: |
                  ./main -h
                  time ./main -m "$(echo "$(basename "${{ env.MODEL_openvino_URL }}")" | sed 's/\-models.zip$//').bin" -f ${{ env.AUDIO_FILENAME }} -l ${{ env.language }} --prompt ${{ env.initial_prompt }} -fa
              if: ${{ contains(matrix.platform, 'ubuntu') && contains(matrix.make-args, 'GGML_OPENBLAS=1') }}             

            - name: Test compiled file (Windows) 1
              if: contains(matrix.platform, 'windows')
              run: |
                .\build\bin\Release\main -h
                .\build\bin\Release\main -m "$("$("${{ env.MODEL_openvino_URL }}" -split "/" | Select-Object -Last 1)".Replace("-models.zip", ".bin"))" -f ${{ env.AUDIO_FILENAME }} -l ${{ env.language }} --prompt ${{ env.initial_prompt }} -fa

