name: X1
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:


jobs:
  check-bats-version:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    steps:
      # - uses: actions/checkout@v4
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      - name: Ununtu Test 1
      - run: |
          echo "now=$(TZ="Asia/Hong_Kong" date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
          echo -e "\nThe Current Folder                     : $(pwd) \n"
          ls -al
          echo -e "\nThe path of GITHUB_ENV                 : "
          echo $GITHUB_ENV
          echo -e "\nThe variable of GITHUB_ENV : "
          cat $GITHUB_ENV
          echo -e "\nThe variable of PATH : "
          echo $PATH
