name: Testing Windows x86-64
run-name: Testing Windows
on:
  workflow_dispatch:

jobs:
  Testing-0:
    runs-on: windows-2022
    steps:
      - name: Check Environment 0
        run: |
          "`nCurrent Folder : $(pwd)`n"
          ls
          echo -e "The path of GITHUB_ENV : $env:GITHUB_ENV \n"
          echo -e "\nThe content of GITHUB_ENV : \n"
          cat $env:GITHUB_ENV

      - name: Check Environment 1
        run: |
          cmake --version
          cmake --help