name: Testing Windows x86-64
run-name: Testing Windows
on:
  workflow_dispatch:

env:
  CMAKE_BUILD_TYPE: Release

jobs:
  Testing-0:
    permissions:
      contents: write
    runs-on: windows-2022
    steps:
      - name: Set default environment variables for Windows
        run: |
          echo "CMAKE_BUILD_TYPE=${{ inputs.cmake_build_type || 'Release' }}" >> $GITHUB_ENV
          $now =(Get-Date).ToUniversalTime().AddHours(8).ToString("yyyyMMdd-HHmmss")
          echo "now=$now" >> $env:GITHUB_ENV

      - name: Check Environment 0
        run: |
          echo "`nThe current time    : ${{ env.now }} "
          echo "`nThe Current folder  : $(pwd)"
          ls
          echo "`nThe path of GITHUB_ENV : $env:GITHUB_ENV `n"
          echo "`nThe variable of GITHUB_ENV : `n"
          echo $env:GITHUB_ENV
          echo "`nThe variable of PATH"
          echo $env:PATH
          echo "`nThe variable of current environment"
          Get-Variable

      - name: Check Environment 1
        run: |
          echo "`nThe version of current PowerShell    : "
          echo $PSVersionTable

      - name: Check Environment 2
        run: |
          cmake --version
          Measure-Command -Expression {cmake --help}