name: Testing OS Windows Server 2022
run-name: build for Windows
on:
  # push:
  #   paths:
  #     - .github/workflows/test1.yml
  workflow_dispatch:
# on: [push]

jobs:
  build-windows-x64-T1:
    runs-on: windows-latest

    strategy:
      matrix:
        build: [Release]
        arch: [x64]
        # arch: [Win32, x64]
        sdl2: [ON]
        include:
          # - arch: Win32
          #   s2arc: x86
          #   jnaPath: win32-x86
          - arch: x64
            s2arc: x64
            jnaPath: win32-x86-64
          - sdl2: ON
            s2ver: 2.28.5

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Fetch SDL2 and set SDL2_DIR
        if: matrix.sdl2 == 'ON'
        run: |
          C:/msys64/usr/bin/wget.exe -qO sdl2.zip https://github.com/libsdl-org/SDL/releases/download/release-${{ matrix.s2ver }}/SDL2-devel-${{ matrix.s2ver }}-VC.zip
          7z x sdl2.zip
          echo "SDL2_DIR=$env:GITHUB_WORKSPACE/SDL2-${{ matrix.s2ver }}/cmake" >> $env:GITHUB_ENV
          echo "`nPATH"
          echo $env:PATH
          echo "`nSDL2_DIR"
          echo $env:SDL2_DIR
          echo "`nGITHUB_ENV"
          echo $env:GITHUB_ENV
          dir

      - name: Configure
        run: >
          cmake -S . -B ./build -A ${{ matrix.arch }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build }}
          -DWHISPER_SDL2=${{ matrix.sdl2 }}

      - name: Build
        run: |
          cd ./build
          msbuild ALL_BUILD.vcxproj -t:build -p:configuration=${{ matrix.build }} -p:platform=${{ matrix.arch }}

      - name: Copy SDL2.dll
        if: matrix.sdl2 == 'ON'
        run: copy "$env:SDL2_DIR/../lib/${{ matrix.s2arc }}/SDL2.dll" build/bin/${{ matrix.build }}

      - name: Testing 1
        run: |
          dir
          dir build/bin/${{ matrix.build }}
          ./build/bin/${{ matrix.build }}/main.exe -h

      # - name: Upload dll
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ matrix.jnaPath }}_whisper.dll
      #     path: build/bin/${{ matrix.build }}/whisper.dll

      - name: Upload binaries
        if: matrix.sdl2 == 'ON'
        uses: actions/upload-artifact@v4
        with:
          name: build-windows-x86-64-cpu-msbuild_T1
          path: build/bin/${{ matrix.build }}
